// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPS_FullStack.Server.AppDbContext;

#nullable disable

namespace TPS_FullStack.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508051043_#007_Add Relation to Topic table")]
    partial class _007_AddRelationtoTopictable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("Kichhoat")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chungchi", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("Donvicap")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool?>("Khongsudung")
                        .HasColumnType("bit");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<decimal>("Thoigiansudung")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.HasKey("MaID");

                    b.ToTable("Chungchi");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chungchi_Hocvien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ChungchiID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Chungchi_Donvicap")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Chungchi_Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Chungchi_Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<decimal>("Chungchi_Thoigiansudung")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("HocvienID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("KhoahocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("Khongsudung")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Ngaycap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngayhethan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaID");

                    b.ToTable("Chungchi_Hocvien");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende", b =>
                {
                    b.Property<string>("MaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<bool?>("Khongsudung")
                        .HasColumnType("bit");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.HasKey("MaID");

                    b.ToTable("Chuyende");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Cauhoi", b =>
                {
                    b.Property<string>("MaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ChuyendeID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<decimal>("Diem")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("MaID");

                    b.HasIndex("ChuyendeID");

                    b.ToTable("Chuyende_Cauhoi");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Dapan", b =>
                {
                    b.Property<string>("MaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Chuyende_CauhoiID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("Dung")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("MaID");

                    b.HasIndex("Chuyende_CauhoiID");

                    b.ToTable("Chuyende_Dapan");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Giangvien", b =>
                {
                    b.Property<string>("MaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ChuyendeID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("GiangvienID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("MaID");

                    b.HasIndex("ChuyendeID");

                    b.ToTable("Chuyende_Giangvien");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Tailieu", b =>
                {
                    b.Property<string>("MaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ChuyendeID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool?>("Khongsudung")
                        .HasColumnType("bit");

                    b.Property<decimal>("Kichthuoc")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Loaitailieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tieude")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("MaID");

                    b.HasIndex("ChuyendeID");

                    b.ToTable("Chuyende_Tailieu");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Giangvien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaID");

                    b.HasIndex("UserId");

                    b.ToTable("Giangvien");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Hocvien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaID");

                    b.HasIndex("UserId");

                    b.ToTable("Hocvien");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Khoahoc", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ChungchiID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<decimal>("Diemdat")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool?>("Khongsudung")
                        .HasColumnType("bit");

                    b.Property<string>("LichhocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(450)");

                    b.HasKey("MaID");

                    b.ToTable("Khoahoc");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Khoahoc_Chuyende", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ChuyendeID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("KhoahocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("MaID");

                    b.ToTable("Khoahoc_Chuyende");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Khoahoc_Giangvien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("GiangvienID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("KhoahocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("MaID");

                    b.ToTable("Khoahoc_Giangvien");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Khoahoc_Hocvien", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<decimal>("Diem")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Dieuchinh")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("HocvienID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("KhoahocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("MaID");

                    b.ToTable("Khoahoc_Hocvien");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Khoahoc_dmTrangthai", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("KhoahocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("MaID");

                    b.ToTable("Khoahoc_DmTrangthai");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Lichhoc", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<decimal>("Sobuoihoc")
                        .HasColumnType("DECIMAL(4,1)");

                    b.Property<decimal>("Thoigianhoc")
                        .HasColumnType("DECIMAL(4,1)");

                    b.Property<string>("Thu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("MaID");

                    b.ToTable("Lichhoc");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Lichhoc_Ct", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("Dengio")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiangvienID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("LichhocID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<decimal>("Lichhoc_Thoigianhoc")
                        .HasColumnType("DECIMAL(4,1)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tugio")
                        .HasColumnType("datetime2");

                    b.HasKey("MaID");

                    b.ToTable("Lichhoc_Ct");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Lichhoc_Ct_Diemdanh", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("HocvienID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Lichhoc_CtID")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("MaID");

                    b.ToTable("Lichhoc_Ct_Diemdanh");
                });

            modelBuilder.Entity("TPS_FullStack.Server.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("refreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Cauhoi", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.Chuyende", "Chuyende")
                        .WithMany("Chuyende_Cauhois")
                        .HasForeignKey("ChuyendeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuyende");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Dapan", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.Chuyende_Cauhoi", "Chuyende_Cauhoi")
                        .WithMany("Chuyende_Dapans")
                        .HasForeignKey("Chuyende_CauhoiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuyende_Cauhoi");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Giangvien", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.Chuyende", null)
                        .WithMany("Chuyende_Giangviens")
                        .HasForeignKey("ChuyendeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Tailieu", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.Chuyende", "Chuyende")
                        .WithMany("Chuyende_Tailieus")
                        .HasForeignKey("ChuyendeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuyende");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Giangvien", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Hocvien", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TPS_FullStack.Server.RefreshToken", b =>
                {
                    b.HasOne("TPS_FullStack.Server.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende", b =>
                {
                    b.Navigation("Chuyende_Cauhois");

                    b.Navigation("Chuyende_Giangviens");

                    b.Navigation("Chuyende_Tailieus");
                });

            modelBuilder.Entity("TPS_FullStack.Server.Entities.Chuyende_Cauhoi", b =>
                {
                    b.Navigation("Chuyende_Dapans");
                });
#pragma warning restore 612, 618
        }
    }
}
