on:
  push:
    branches:
      -  develop
jobs:
  my_job:
    name: testing
    runs-on: windows-2022
    steps:
      - name: Go to Server project
        run: cd ..\TPS_FullStack.Server\
      - name: Build .NET Core
        run: |
          dotnet restore
          dotnet build
